### ISSUE TITLE
can't find fingerprint on xaga

### ISSUE THREAD

**Issue by theeleventhname** [ItsVixano-releases/issues#10]
### Build Date

21-20240415-UNOFFICIAL-xaga

### Device

xaga

### LineageOS Version

lineage-21

### Describe the Bug

cant find fingerprint sensor ,even set pin passwd(sorry for that I dont get the right sensor in hw info screenshots)

![Screenshot_20240416-190036_Permission controller](https://github.com/ItsVixano-releases/issues/assets/31616713/4221b876-b16d-46cc-9753-3dc060803956)
![Screenshot_20240416-190114_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/ca9ff44c-b018-4cf6-89f1-94392b7c5db7)
![Screenshot_20240416-190118_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/cf9a2bd8-5887-46d9-ab18-d384c167d99c)
![Screenshot_20240416-190134_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/8e1cb105-2cb9-4bbb-888f-96d21c1ea205)
![Screenshot_20240416-190139_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/64c8503e-0974-4566-9efe-1f86355065a8)
![Screenshot_20240416-190143_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/cbd2e122-b0e1-4e6e-88f7-108201f75235)
![Screenshot_20240416-190147_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/99f98f5d-77ac-4ce1-b48e-9673b594adc5)
![Screenshot_20240416-190152_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/d6b5c9ac-2fb8-4766-9150-5e2488979243)
![Screenshot_20240416-190838_Phone Probe](https://github.com/ItsVixano-releases/issues/assets/31616713/f53054d3-eb21-4fa3-a3b5-694bffdda917)

### Steps to Reproduce

1.flash boot,vendor_boot,dtbo and sideload lineage.zip,power on
2.set password
3.but cant get the fingerprint button

### Expected Behavior

available fingerprint settings~

### Possible Solution

add another type of sensor driver,maybe~

**Comment by ItsVixano** [comment]
No useful info here ... 

Can you please grab a log ?

```
adb root # Enable it on dev option
adb shell
stop vendor.fps_hal
start vendor.fps_hal
"press ctrl + d"
adb logcat -b all > logs.log
```

After send the file `logs.log` here

**Comment by theeleventhname** [comment]
here is the log,and i found that touch sensor was detected as screen_down function ,the screenshot is the details(hope taht help solve the problem)
[logs.log](https://github.com/ItsVixano-releases/issues/files/14997640/logs.log)

**Comment by theeleventhname** [comment]
![Uploading Screenshot_20240416-213024_DevInfo.png…]()

**Comment by theeleventhname** [comment]
![Screenshot_20240416-213024_DevInfo](https://github.com/ItsVixano-releases/issues/assets/31616713/96aa95ad-417f-494d-8c99-212301f00157)

**Comment by VskAwayZ** [comment]
朋友你好，我也刷了这个rom，发现中国电信卡不能用，我看另外一个issue里开发者给出了一个方法，但我不会root，如果你已经root了的话或许可以帮助开发者测试一下，以便修复这个问题 :)

**Comment by theeleventhname** [comment]
here is  permissive_logs.log ，disable selinux and stop+start vendor then catch log as you said
[permissive_logs.log](https://github.com/ItsVixano-releases/issues/files/14998326/permissive_logs.log)

**Comment by theeleventhname** [comment]
> 朋友你好，我也刷了这个rom，发现中国电信卡不能用，我看另外一个issue里开发者给出了一个方法，但我不会root，如果你已经root了的话或许可以帮助开发者测试一下，以便修复这个问题 :)

用payload解包找到boot,然后用magisk的app修补boot,然后进fb刷入对应的boot分区即可获取root,我的电信也不能打电话

**Comment by ItsVixano** [comment]
> here is permissive_logs.log ，disable selinux and stop+start vendor then catch log as you said [permissive_logs.log](https://github.com/ItsVixano-releases/issues/files/14998326/permissive_logs.log)

Mind sending a dmesg as well ??

```
adb root # Enable it on dev option
adb shell
stop vendor.fps_hal
start vendor.fps_hal
dmesg > /sdcard/kernel.log
"press ctrl + d"
adb pull /sdcard/kernel.log
```

Send `kernel.log` here

**Comment by theeleventhname** [comment]
> > here is permissive_logs.log ，disable selinux and stop+start vendor then catch log as you said [permissive_logs.log](https://github.com/ItsVixano-releases/issues/files/14998326/permissive_logs.log)
> 
> Mind sending a dmesg as well ??
> 
> ```
> adb root # Enable it on dev option
> adb shell
> stop vendor.fps_hal
> start vendor.fps_hal
> dmesg > /sdcard/kernel.log
> "press ctrl + d"
> adb pull /sdcard/kernel.log
> ```
> 
> Send `kernel.log` here

okay,here is the kernel.log ,I add some parameters to enable call and sms,that doesnt matter,right?
[Uploading kernel.log…]()

**Comment by theeleventhname** [comment]
> 朋友你好，我也刷了这个rom，发现中国电信卡不能用，我看另外一个issue里开发者给出了一个方法，但我不会root，如果你已经root了的话或许可以帮助开发者测试一下，以便修复这个问题 :)

你先执行adb  root 再执行adb remount来保证system分区可以被读写，然后进入adb shell,用echo xxxx > xxxx的方式来追加那几个参数到文件末尾，之后重启就行了，我试了后能正常用电信打电话接短信了

**Comment by ItsVixano** [comment]
> Uploading kernel.log…

Uhm, mind checking the link again :see_no_evil: ?

**Comment by theeleventhname** [comment]
> > Uploading kernel.log…
> 
> Uhm, mind checking the link again 🙈 ?
maybe my network causes bad～
[kernel.log](https://github.com/ItsVixano-releases/issues/files/14999931/kernel.log)

**Comment by ItsVixano** [comment]
> > > Uploading kernel.log…
> > 
> > 
> > Uhm, mind checking the link again 🙈 ?
> > maybe my network causes bad～
> > [kernel.log](https://github.com/ItsVixano-releases/issues/files/14999931/kernel.log)

Uhm ok so, i'll try to make that working on the next update (i'll release it during this week or so) (i'm sure is due to the old blobs we are using right now).

For now keep this ticket open :D

**Comment by theeleventhname** [comment]
sorry for that its time

> > > > Uploading kernel.log…
> > > 
> > > 
> > > Uhm, mind checking the link again 🙈 ?
> > > maybe my network causes bad～
> > > [kernel.log](https://github.com/ItsVixano-releases/issues/files/14999931/kernel.log)
> 
> Uhm ok so, i'll try to make that working on the next update (i'll release it during this week or so) (i'm sure is due to the old blobs we are using right now).
> 
> For now keep this ticket open :D

really？ thx for your job🥳

**Comment by ItsVixano** [comment]
Closing the ticket due to inactivity. People on telegram have reported that both `fpc` and `goodix` fingerprint hardware work fine on newer versions. Feel free to reopen it if the problem persists :D.
