### ISSUE TITLE
failed to connect to WiFi with WPA3 security

### ISSUE THREAD

**Issue by paolo-sz** [ItsVixano-releases/issues#11]
### Build Date

21-20240623-UNOFFICIAL-daisy

### Device

daisy

### LineageOS Version

lineage-21

### Describe the Bug

Well, not really sure this could be considered a bug or even just an issue... It's up to you to decide if this is a reasonable "issue" to address, if so I will be available to provide any additional information, logs and so on..
The phone is perfectly able to connect to a router with a WPA2-Personal security but fails to connect to a repeater with WPA2+WPA3 security. Downgrading the repeater to WPA2 (CCMP) solve the connection failure.

### Steps to Reproduce

1. connect to a WPA3 access point

### Expected Behavior

Ability to connect to latest security standard access points.

**Comment by jaromirk** [comment]
Adding more context. With latest build 20240623 I was not able to connect to WPA2 and WPA2/WPA3 mixed mode. If I switched my Mikrotik to pure WPA3, all worked. I downgraded to build 20240515 and now it works. (in wifi description it says WPA/WPA2-Personal, but my network (and my samsung device) says WPA2/WPA3-Personal. So I guess there were some WPA3 changes in latest build that does not work.

**Comment by ItsVixano** [comment]
I'm not 100% sure about this, but it looks like [this](https://github.com/LineageOS/android_external_wpa_supplicant_8/commit/f99885cc672a583a51144dbb24b9bcc14350a37c) upstream commit seems to cause that issue.

`msm8953` uses `CONFIG_DRIVER_NL80211_QCA` and it will always return WPA2 no matter what (whereas with the old behaviour it would check for both WPA3 and WPA2).

Not sure if there's an upstream `prima` kernel module commit (or something to backport from `qcacld` ). Will probably just revert the commit for now.

**Comment by jaromirk** [comment]
If you need anything from me, just let me know. Its just my test phone, now running 20240515.

**Comment by catgangdev** [comment]
After A14 QPR3, WPA3 is no longer supported on old devices due to encryption changes on WPA3 which are not supported by old legacy wifi chip. Maybe will work if someone reverse it

**Comment by jaromirk** [comment]
Interesting was, that WPA3 was actually working. But WPA2/ WPA2+WPA3 did not.

**Comment by ItsVixano** [comment]
Build `20240715` includes the pre-QPR3 `wpa_supplicant` binary, should works fine now *hopefully*

**Comment by jaromirk** [comment]
tried to update (from Android OS) but says "verification failed".

**Comment by ItsVixano** [comment]
> tried to update (from Android OS) but says "verification failed".

You are probably running the old version, it requires a manual flash (check the release notes :D)

**Comment by jaromirk** [comment]
perfect. All works (wifi). Thanks!

**Comment by ItsVixano** [comment]
Closing the ticket due to inactivity. Feel free to reopen it if the problem persists :D.
