### ISSUE TITLE
Phone got FBE ecnrypted due to wrong pin save in the rom

### ISSUE THREAD

**Issue by KiraiEEE** [ItsVixano-releases/issues#19]
### Build Date

21-20241015-UNOFFICIAL-miatoll

### Device

miatoll

### LineageOS Version

lineage-21

### Describe the Bug

I encountered a problem after installing this version of Lineage OS on my Redmi Note 9S. After setting a new PIN, I was unable to unlock the device, as it incorrectly indicated that the PIN was wrong, even though I remembered it correctly; it’s the same PIN I use all the time. This resulted in the phone becoming encrypted with File-Based Encryption (FBE), preventing any access or recovery attempts. I Somehow managed to install a different ROM (CRDroid), but I continue to see the message from OrangeFox stating, "OrangeFox will not recreate /data/media on an FBE device. Please reboot into your rom to create /data/media." Each time I format the data or perform similar actions, I'm hesitant to reinstall Lineage OS to see if I can input a new PIN and potentially overwrite the old FBE encryption, as I'm concerned about encountering similar issues again.

### Steps to Reproduce

1. Install the ROM
2. Set a New PIN:
3. Attempt to Unlock:
After setting the PIN, attempt to unlock the device using the newly set PIN.
Observe Error Message:
Note that the device incorrectly indicates that the PIN is wrong, despite being correct.

4. Device Encryption:

Observe that the device becomes encrypted with File-Based Encryption (FBE), preventing access.

5. Install a Different ROM:

Boot into recovery (OrangeFox) and install a different ROM (e.g., CRDroid).
Format Data:

Attempt to format the data partition in OrangeFox and observe the message: "OrangeFox will not recreate /data/media on an FBE device. Please reboot into your rom to create /data/media."

### Expected Behavior

After setting a new PIN during the initial setup of Lineage OS, the device should allow access using the correct PIN without any errors.
The device should not become encrypted with File-Based Encryption (FBE) due to a PIN-related issue.
If a different ROM (e.g., CRDroid) is successfully installed, the data partition should be accessible without displaying messages about FBE.
Formatting the data partition should recreate the /data/media directory without encountering any restrictions related to FBE.

### Possible Solution

idk but im literally in trouble cuz i cant afford new phone

**Comment by ItsVixano** [comment]
> Boot into recovery (OrangeFox)

I do not support custom recoveries other than Lineage Recovery.

**Comment by KiraiEEE** [comment]
> > Boot into recovery (OrangeFox)
> 
> I do not support custom recoveries other than Lineage Recovery.

sorry but what u recommend me to do plz help
