### ISSUE TITLE
The pin code is not installed on the screen

### ISSUE THREAD

**Issue by zhhhh-dev** [ItsVixano-releases/issues#23]
### Build Date

22-20241224-UNOFFICIAL-miatoll

### Device

miatoll

### LineageOS Version

lineage-22

### Describe the Bug

Press Security & privacy, next Device unlock, -> Screen lock, ->PIN-> any pin, then The pin code is not installed on the screen

### Steps to Reproduce

1.Press Security & privacy, next Device unlock, Screen lock, PIN
2. press any pin

### Logs

[logcat.log](https://github.com/user-attachments/files/18263708/logcat.log)

### Expected Behavior

Press Security & privacy, next Device unlock, -> Screen lock, ->PIN-> any pin, then The pin code is installed on the screen

**Comment by ItsVixano** [comment]
Did you install it according to the wiki ?
Did you follow each step correctly ?

**Comment by zhhhh-dev** [comment]
>>Did you install it according to the wiki ?
yes
ps:  I had the project pixelage firmware, and I didn't install miui this time.  I'll try to install miui first.

**Comment by zhhhh-dev** [comment]
I flashed miui first and then it became normal. I'm sorry to bother you.
