### ISSUE TITLE
(LineageOS Daisy) Doesn't find updates anymore from settings app

### ISSUE THREAD

**Issue by MaxWasTakenYT** [ItsVixano-releases/issues#3]
### Build Date

20-20231012-UNOFFICIAL-daisy

### Device

daisy

### LineageOS Version

lineage-20

### Describe the Bug

As the title says, it always worked, but now when checking for updates it doesn't work anymore
I tried manually refreshing too, nothing tho

### Steps to Reproduce

Not sure how, just from a day to another it stopped working

### Expected Behavior

To be able to find and install updates

**Comment by MaxWasTakenYT** [comment]
i'm now trying to manually update the phone using the "local update" feature
do i have to select the img or the zip? (using the [official releases page](https://github.com/ItsVixano-releases/LineageOS_daisy/releases))

**Comment by ItsVixano** [comment]
no, it is always good practice to make a backup before upgrading.

**Comment by MaxWasTakenYT** [comment]
sorry for the misunderstanding, it finished "local updating" and its on android 14 (lineage os 21 i think)
so i guess it works like this too

**Comment by MaxWasTakenYT** [comment]
closed it since it's solved now, sorry for the hassle
