### ISSUE TITLE
Phone calls and SMS do not work

### ISSUE THREAD

**Issue by ZhangYaoan** [ItsVixano-releases/issues#4]
### Build Date

21-20240324-UNOFFICIAL-xaga

### Device

xaga

### LineageOS Version

lineage-21

### Describe the Bug

Phone calls (VoLTE/Vo5G) and SMS do not work.
Mobile network operator: China Telecommunications (46011 - 中国电信)

#### For phone call:
1. Open "Phone" app
2. Make a phone call
3. Error: Mobile network not available
#### For SMS:
1. Open "Messaging" app
2. Send a message
3. Error: Not sent. Tap to try again.
5. I tried to send it again, but it still doesn't work.

P.S. It can't receive SMS or phone call, too.

### Logs

[linage_xaga_bug_logs.zip](https://github.com/ItsVixano-releases/issues/files/14810085/linage_xaga_bug_logs.zip)

### Expected Behavior

Make a phone call, send a SMS and receive phone call / SMS successfully.

### Possible Solution

Maybe there is something wrong with VoLTE / Vo5G.

**Comment by ItsVixano** [comment]
Looks like we need to enable it for the others carriers as well ? 

Can you try setting these props on system/build.prop (requires `adb root` & `adb remount`, just a warning, this will break OTA Updates, you'd need to flash manually the next update) ??

```
persist.dbg.volte_avail_ovr=1
persist.dbg.vt_avail_ovr=1
persist.dbg.wfc_avail_ovr=1
```

**Comment by ZhangYaoan** [comment]
Thanks a lot. After setting them, they worked.

**Comment by ItsVixano** [comment]
Mind checking if the issue persist on `20240415` build ?

**Comment by ItsVixano** [comment]
Closing since i got confirmation that is fine on `20240419` build.
