### ISSUE TITLE
Fingerprint setting crash

### ISSUE THREAD

**Issue by paolo-sz** [ItsVixano-releases/issues#5]
### Build Date

21-20240324-UNOFFICIAL-daisy

### Device

daisy

### LineageOS Version

lineage-21

### Describe the Bug

the app settings crashes when trying to add or modify a fingerprint so no fingerprint can be added or modified outside the initial first time setup wizard (clean flash)

### Steps to Reproduce

1. go to settings -> privacy & security -> device unlock -> fingerprint
(not really sure of the english "name" of each menu entry... they are a reasonable translation from my italian menu...)
sometimes it crashes directly at his point and sometimes it crashes after asking the PIN

### Logs

http://oshi.at/ekag

### Expected Behavior

well... fingerprints management availability without crashes

**Comment by ItsVixano** [comment]
https://review.lineageos.org/c/LineageOS/android_packages_apps_Settings/+/387311

Well, looks like a fix for it has been merged already, wait for the next OTA :D

**Comment by paolo-sz** [comment]
I confirm the issue is solved with the latest <code>20240415</code> build
