### ISSUE TITLE
Blur does not work

### ISSUE THREAD

**Issue by ZhangYaoan** [ItsVixano-releases/issues#6]
### Build Date

21-20240324-UNOFFICIAL-xaga

### Device

xaga

### LineageOS Version

lineage-21

### Describe the Bug

System blur does not work. 
For example, in recent tasks screen, there is expected to be blur. But actually, it is transparent. (In other ROMs, there is blur.)
![Screenshot_20240403-211939_Trebuchet](https://github.com/ItsVixano-releases/issues/assets/110913909/93c47986-14e8-4839-a200-ff014245fe69)

### Steps to Reproduce

N/A

### Logs

[log.zip](https://github.com/ItsVixano-releases/issues/files/14854485/log.zip)

### Expected Behavior

N/A

**Comment by ItsVixano** [comment]
AOSP default behaviour is to not enable blur. You can enable it by setting `ro.surface_flinger.supports_background_blur=1`, however I won't do this in my builds for performance reasons.
