### ISSUE TITLE
Wifi does not turn on in the first try. 

### ISSUE THREAD

**Issue by godse69gandhi** [ItsVixano-releases/issues#8]
### Build Date

21-20240415-UNOFFICIAL-xaga

### Device

xaga

### LineageOS Version

lineage-21

### Describe the Bug

The wifi tile on quick settings doesn't work on the first try , need to turn it (on>off>on again) to connect to wifi. The same happens with the actual wifi switch in settings app as well. 

### Steps to Reproduce

1. turn off wifi and wait for 10secs.
2. Now turn on wifi through quick settings wifi tile or the wifi switch in settings app , will be stuck on turning on but not connect to wifi. 
3. turn it off and on again , now it will connect to wifi.

### Logs

https://oshi.at/MMyf/IMYz.txt

### Expected Behavior

The issue is not limited to wifi tile , it persists even when you turn on wifi through settings app. need to turn it on>off>on in this exact order to connect to wifi.

**Comment by ItsVixano** [comment]
Closing the ticket due to inactivity. Feel free to reopen it if the problem persists :D.
